### ISSUE TITLE
pcode compatibility

### ISSUE THREAD

**Issue by Simi699** [Planet-Source-Code/vlad-vissoultchev-compact-in-process-multi-threading-a-folderwatcher-with-sample-ui__1-36373#1]
Hello  wqweto,

What are the changes to be done for the code to run even when compiled in pcode without access violation which you already pointed out with trik where I raised the same issue.

**Comment by wqweto** [comment]
@Simi699 I don't see much chances this running in p-code.

**Comment by Simi699** [comment]
I compiled FolderWatcher to p-code and generated FolderWatcher.dll which I added in project references in Project1 standard exe project and compiled it to p-code.When I have run it outside compiler by doubleclicking on Project1.exe ,  Form1 GUI is displayed in which I selected a folder by clicking on **Address** button  and when I clicked on **Go** button the application crashes.All this works if I use native code compiling for both  FolderWatcher  and Project1 projects.
